### ISSUE TITLE
Evaluation Criteria for the Final project

### ISSUE THREAD

**Issue by alishsuper** [yungyuc/nsdhw_19au#106]
Dear @yungyuc! In the last lecture you showed us a list of your evaluation criteria. Could you please share it with us? I can't find it in our lecture github repository.
Thanks!

**Comment by yungyuc** [comment]
Thanks for bring this up.  It's available at https://github.com/yungyuc/nsdhw_19au/tree/master/term_project#grading-guideline-subject-to-change .
