### ISSUE TITLE
HW3 Document clarification

### ISSUE THREAD

**Issue by alan0201tw** [yungyuc/nsdhw_19au#43]
In the document of hw3 ( hw3/README.rst )...

The 'Question' section states that we need to implement a matrix-vector multiplication program and compare it with DGEMV.
While the 'Grading guideline' section states that a matrix-matrix multiplication function and its comparison with DGEMM is required.

Just wondering whether it's a typo, or do we need to implement both cases for this assignment?

Also, the indentation in the file seems to be causing some false preview on Github's page.

Thank you in advance for responding!

**Comment by tigercosmos** [comment]
It seems that Github does not support `.rst` well, I fixed some.

About the question, ping @yungyuc

**Comment by yungyuc** [comment]
Thank you @alan0201tw for spotting the typo.  It should be only matrix-matrix multiplication and DGEMM.
