### ISSUE TITLE
alishsuper term project proposal is in the wrong directory

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/nsdhw_19au#53]
@alishsuper you are placing your proposal file directly in `term_proposal/` directory but I asked you to put it in *a sub-directory using exactly your GitHub username*.  In your case it should be `term_proposal/alishsuper/`.  Please use another PR to correct it or the proposal is considered not submitted.

**Comment by alishsuper** [comment]
I created new pull request https://github.com/yungyuc/nsdhw_19au/pull/51. Please take a look. Thanks!

**Comment by alishsuper** [comment]
I created new pull request https://github.com/yungyuc/nsdhw_19au/pull/58. Old one was with some mistakes so I decided that it would be easier if I just create new one. Please check it. Thanks!
