### ISSUE TITLE
About set $PRELOAD_MKL in hw3

### ISSUE THREAD

**Issue by titaneric** [yungyuc/nsdhw_19au#65]
Hi,

I have finished the hw3, but I notice that the grader will not set the environment variable `PRELOAD_MKL` in the command. It seems that it just determines whether it sets `LD_PRELOAD` or not with the condition set  `PRELOAD_MKL` in the `validate.py` . Because it just runs before `make test` we will not have the chance to set `PRELOAD_MKL` before the grader execute `validate.py`.

So I have the question is that does this thing (set `PRELOAD_MKL`) need to be done by ourself, or the grader will set it before validate our homework?

**Comment by yungyuc** [comment]
@titaneric thanks for asking.  I will ask the grade to test both cases (set `PRELOAD_MKL` or not) and your work is considered good as one of the case passes.  And I'll add that to the homework description in case we forget about it.

As I mentioned in `validate.py` it's to work around an issue in the AMI conda MKL installation.  Students shouldn't need to worry about it.  And it's probably not a problem if you don't try to use cmake to build the pybind11 module.
